astra_db:
  collection_name: "ecommercedata"

# embedding_model:
#   provider: "google"
#   model_name: "models/gemini-embedding-001"

embedding_model:
  provider: "openai"
  model_name: "models/text-embedding-3-large"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
